# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.13-browsers

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install project package
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      ## Test
      - run:
          name: Linting
          command: npm run lint

      ## Build
      - run:
          name: Building the package
          command: npm run ng build --prod

      - persist_to_workspace:
          root: /home/circleci
          paths:
            -project

  deploy:
    docker:
      - image: circleci/python:3.6.8-jessie
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: AWS S3
          command: aws s3 sync ~/project/dist/arkham-log s3://arkham-log.com/ --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master